export default {
    SET_LOADING_STORE: 'store/loading',
    RESET_STORE: 'store/reset',
    SET_STORE: 'store/load/success',
    SET_PRODUCTS: 'product/load/success',
    SET_PRODUCT_LOADING: 'product/loading',
    SET_STORE_CATEGORIES: 'categories/load/success',
    SET_ORDERS: 'orders/load/success',
    SET_ORDER_LOADING: 'order/loading',
    SET_ATTRIBUTES: 'attributes/load/success',
    SET_ATTRIBUTE_LOADING: 'attributes/loading',
    SET_WAREHOUSES: 'warehouses/load/success',
    SET_STOCK_LOADING: 'stock/loading',
    SET_STOCKS: 'stock/load/success',
    SET_CUSTOMERS: 'customers/load/success',
    SET_CUSTOMERS_LOADING: 'customer/loading',
    SET_ENABLE_SALE_CHANNELS: 'enable-sale-channels/load/success',
};
