export default {
    RELOAD_FILTER: 'order/RELOAD_FILTER',
    CHANGE_TEXT_SEARCH: 'orders/CHANGE_TEXT_SEARCH',
    CHANGE_STATUS: 'orders/CHANGE_STATUS',
    CHANGE_PAGINATION: 'orders/CHANGE_PAGINATION',
    CHANGE_FILTER: 'orders/CHANGE_FILTER',
    REMOVE_FILTER: 'orders/REMOVE_FILTER',
};
