const types = {
    INIT_STATE: 'billings/INIT_STATE',
    UPDATE_PACKAGES: 'billings/UPDATE_PACKAGES',
    UPDATE_BILLING_CYCLE: 'billings/UPDATE_BILLING_CYCLE',
    UPDATE_PAYMENT_METHODS: 'billings/UPDATE_PAYMENT_METHODS',
    CHANGE_VALUE_FIELD: 'billings/CHANGE_VALUE_FIELD',
    CHANGE_CYCLE_FIELD: 'billings/CHANGE_CYCLE_FIELD',
    GET_ALL_PACKAGES: 'billings/GET_ALL_PACKAGES',
    GET_PACKAGES_ACTIVE: 'billings/GET_PACKAGES_ACTIVE',
    GET_PACKAGES_INACTIVE: 'billings/GET_PACKAGES_INACTIVE',
    SET_LOADING: 'billings/SET_LOADING',
    SET_WARNING_EXPERIED_PACKAGE: 'billings/SET_WARNING_EXPERIED_PACKAGE',
    SET_WARNING_EXPERIED_TRY: 'billings/SET_WARNING_EXPERIED_TRY',
    SET_NAME_PACKAGES_EXPERIED: 'billings/SET_NAME_PACKAGES_EXPERIED',
    SET_PACKAGES_NEED_EXTENED: 'billings/SET_PACKAGES_NEED_EXTENED',
    SET_TRANSACTION_CODE: 'billings/SET_TRANSACTION_CODE',
    GET_HISTORY_PAYMENT: 'billings/GET_HISTORY_PAYMENT',
};

export default types;
