export default {
    LOAD_REPORT: 'homepage/LOAD_REPORT',
    LOAD_REPORT_SUCCESS: 'homepage/LOAD_REPORT_SUCCESS',
    LOAD_REPORT_FAILED: 'homepage/LOAD_REPORT_FAILED',

    SELECT_TYPE_TIME: 'homepage/SELECT_TYPE_TIME',
    SELECT_WAREHOUSE: 'homepage/SELECT_WAREHOUSE',
};
